<h1 id="squeezing-the-most-utility-from-your-models">Squeezing the Most Utility from Your Models</h1>
<p>In a <a href="https://win-vector.com/2020/08/07/dont-use-classification-rules-for-classification-problems/">previous article</a> we discussed why it’s a good idea to prefer probability models to “hard” classification models, and why you should delay setting “hard” classification rules as long as possible. But decisions have to be made, and eventually you will have to set that threshold. How do you do it?</p>
<p>A good threshold balances classifier precision/recall or sensitivity/specificity in a way that best meets the project or business needs. One way to quantify and think about this balance is the notion of <em>model utility</em>, which maps the performance of a model to some notion of the value achieved by that performance. In this article, we demonstrate the use of <a href="https://winvector.github.io/sigr/reference/model_utility.html"><code>sigr::model_utility()</code></a> to estimate model utility and pick model thresholds for classification problems.</p>
<h2 id="the-example-problem">The Example Problem</h2>
<p>Let’s imagine that we have a sales application, and we are trying to decide which prospects to target. We want to build a model that predicts the probability of conversion, based on certain prospect characteristics.</p>
<p>For our example, suppose we have a population where true positives are relatively rare (about 1% of the population), and we have trained a model that returns predictions like this on an evaluation set, <code>d</code>:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw">library</span>(WVPlots)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="kw">DoubleDensityPlot</span>(d, <span class="st">&quot;predicted_probability&quot;</span>, <span class="st">&quot;converted&quot;</span>,</span>
<span id="cb1-3"><a href="#cb1-3"></a>                  <span class="dt">title =</span> <span class="st">&quot;Model score distribution by true outcome&quot;</span>)</span></code></pre></div>
<p><img src="UtilityExample_files/figure-gfm/unnamed-chunk-2-1.png" /><!-- --></p>
<p>(For the data generation code, see <a href="https://github.com/WinVector/sigr/blob/main/extras/UtilityExample.Rmd">the source code for this article</a>).</p>
<p>We want to contact prospects with a higher probability of converting; that is, prospects who score above a certain threshold. How how do we set that threshold? Note that the usual default threshold of 0.5 will fail spectacularly with this model, since both positive and negative examples score quite low. This is not uncommon in low positive prevalence situations.</p>
<h2 id="picking-a-threshold-based-on-model-performance">Picking a threshold based on model performance</h2>
<p>We might try picking the threshold by looking at model performance. Let’s look at precision (the probability that a sample scored as “true” really is true) and recall (the fraction of conversions found) as a function of threshold.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="kw">ThresholdPlot</span>(d, <span class="st">&quot;predicted_probability&quot;</span>, <span class="st">&quot;converted&quot;</span>,</span>
<span id="cb2-2"><a href="#cb2-2"></a>              <span class="dt">title =</span> <span class="st">&quot;Precision and Recall as a function of threshold&quot;</span>,</span>
<span id="cb2-3"><a href="#cb2-3"></a>              <span class="dt">metrics =</span> <span class="kw">c</span>(<span class="st">&quot;precision&quot;</span>, <span class="st">&quot;recall&quot;</span>))</span></code></pre></div>
<p><img src="UtilityExample_files/figure-gfm/unnamed-chunk-3-1.png" /><!-- --></p>
<p>For the sake of efficiency, we’d like to reduce the number of unsuccessful calls as much as possible, which implies we’d like a decision policy with high precision. The best precision we can get with this model occurs at a threshold of around 0.034 or 0.035 or so, and at that point the recall is quite low. Is that classifier good enough for our business needs? This can be hard to tell, as the business needs are likely in dollars, rather than in false positive/false negatives, and so on.</p>
<h2 id="picking-a-threshold-based-on-model-utility">Picking a threshold based on model <em>utility</em></h2>
<p>The way to decide if a possible threshold meets business needs is to attach utilities to the decisions – right and wrong – that the model will make. To do this, we need to assign costs and rewards to contacting (or not contacting) a prospect.</p>
<p>Suppose every contact we make costs $5, and every successful conversion brings in $100 in net revenue. For demonstration purposes, we will also add a small penalty for every missed prospect (one penny), and a small reward for every prospect we correctly ignore (again, one penny). Let’s add those costs to our model frame. (You can leave the last two values at zero, if you prefer).</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>d<span class="op">$</span>true_positive_value &lt;-<span class="st"> </span><span class="dv">100</span> <span class="op">-</span><span class="st"> </span><span class="dv">5</span>   <span class="co"># net revenue - cost</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>d<span class="op">$</span>false_positive_value &lt;-<span class="st"> </span><span class="dv">-5</span>       <span class="co"># the cost of a call</span></span>
<span id="cb3-3"><a href="#cb3-3"></a>d<span class="op">$</span>true_negative_value &lt;-<span class="st">  </span><span class="fl">0.01</span>     <span class="co"># a small reward for getting them right</span></span>
<span id="cb3-4"><a href="#cb3-4"></a>d<span class="op">$</span>false_negative_value &lt;-<span class="st"> </span><span class="fl">-0.01</span>    <span class="co"># a small penalty for having missed them</span></span></code></pre></div>
<p>As we vary the decision threshold, we vary the number of prospects contacted, and the number of successful conversions. We can use the costs and rewards above to calculate the total value (or the <em>total utility</em>) realized by a decision policy over the evaluation set. The threshold that realizes the highest utility is the best threshold to use with a given model (for now, we ignore also modeling uncertainty).</p>
<p>The <code>sigr::model_utility()</code> function can calculate all the costs for various thresholds.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="kw">library</span>(sigr)</span>
<span id="cb4-2"><a href="#cb4-2"></a>values &lt;-<span class="st"> </span><span class="kw">model_utility</span>(d, </span>
<span id="cb4-3"><a href="#cb4-3"></a>                        <span class="dt">model_name =</span> <span class="st">&#39;predicted_probability&#39;</span>, </span>
<span id="cb4-4"><a href="#cb4-4"></a>                        <span class="dt">outcome_name =</span> <span class="st">&#39;converted&#39;</span>)</span></code></pre></div>
<p>The <code>model_utility()</code> function returns a data frame with the following columns (with one example row):</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="kw">t</span>(values[<span class="dv">1</span>, ])</span></code></pre></div>
<pre><code>##                      1                      
## model                &quot;predicted_probability&quot;
## threshold            &quot;0.0002494199&quot;         
## count_taken          &quot;10000&quot;                
## fraction_taken       &quot;1&quot;                    
## true_positive_value  &quot;10070&quot;                
## false_positive_value &quot;-49470&quot;               
## true_negative_value  &quot;0&quot;                    
## false_negative_value &quot;0&quot;                    
## total_value          &quot;-39400&quot;               
## true_negative_count  &quot;0&quot;                    
## false_negative_count &quot;0&quot;                    
## true_positive_count  &quot;106&quot;                  
## false_positive_count &quot;9894&quot;</code></pre>
<p>Each row of <code>values</code> returns the appropriate counts and values for a classifier rule that labels cases as TRUE when <code>predicted_probability &gt;= threshold</code>. Now we can determine the total value returned by the model on our evaluation set, as a function of threshold.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb7-2"><a href="#cb7-2"></a></span>
<span id="cb7-3"><a href="#cb7-3"></a>t_bound &lt;-<span class="st"> </span><span class="fl">0.015</span></span>
<span id="cb7-4"><a href="#cb7-4"></a>vhigh &lt;-<span class="st"> </span><span class="kw">subset</span>(values, threshold <span class="op">&gt;=</span><span class="st"> </span>t_bound) <span class="co"># just look at thresholds &gt;= t_bound</span></span>
<span id="cb7-5"><a href="#cb7-5"></a>p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(vhigh, <span class="kw">aes</span>(<span class="dt">x =</span> threshold, <span class="dt">y =</span> total_value)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb7-6"><a href="#cb7-6"></a><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb7-7"><a href="#cb7-7"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Estimated model utility as a function of threshold&quot;</span>)</span>
<span id="cb7-8"><a href="#cb7-8"></a></span>
<span id="cb7-9"><a href="#cb7-9"></a><span class="co"># find the maximum utility</span></span>
<span id="cb7-10"><a href="#cb7-10"></a>max_ix &lt;-<span class="st"> </span><span class="kw">which.max</span>(vhigh<span class="op">$</span>total_value)</span>
<span id="cb7-11"><a href="#cb7-11"></a>best_threshold &lt;-<span class="st"> </span>vhigh<span class="op">$</span>threshold[max_ix]</span>
<span id="cb7-12"><a href="#cb7-12"></a></span>
<span id="cb7-13"><a href="#cb7-13"></a>p <span class="op">+</span><span class="st"> </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> best_threshold, <span class="dt">linetype=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="UtilityExample_files/figure-gfm/unnamed-chunk-7-1.png" /><!-- --></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="co"># print out some information about the optimum</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>(best_info &lt;-<span class="st"> </span>vhigh[max_ix, <span class="kw">c</span>(<span class="st">&quot;threshold&quot;</span>, <span class="st">&quot;count_taken&quot;</span>, </span>
<span id="cb8-3"><a href="#cb8-3"></a>                             <span class="st">&quot;fraction_taken&quot;</span>, <span class="st">&quot;total_value&quot;</span>)]) <span class="op">%.&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4"></a><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>(.)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">threshold</th>
<th style="text-align: right;">count_taken</th>
<th style="text-align: right;">fraction_taken</th>
<th style="text-align: right;">total_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">9574</td>
<td style="text-align: right;">0.021672</td>
<td style="text-align: right;">427</td>
<td style="text-align: right;">0.0427</td>
<td style="text-align: right;">2159.45</td>
</tr>
</tbody>
</table>
<p>The graph shows that a policy that contacts too many prospects (lower threshold) will <em>lose</em> money (negative utility), while contacting too few prospects (higher threshold) goes to zero utility. The best tradeoff with this model is a threshold of 0.022, which translates to contacting the top 4.27% of the prospects.</p>
<p>If we go back to the precision/recall graph, we see that this optimal threshold actually doesn’t give us the policy with the highest precision, but it makes up for that by making more successful contacts. Picking the threshold from the utility calculation is easier and more reliable than just eyeballing a threshold from the abstract recall/precision graph.</p>
<h3 id="comparing-to-best-possible-performance">Comparing to best possible performance</h3>
<p>We can compare this model’s optimal policy to the best possible performance on this data (contacting all of the successful prospects, and only them), simply by positing a “wizard model” that scores true cases as 1.0 and false cases as 0.0. In this case any threshold between zero and one (say, 0.5) will perform the same. IFor this situation, the <code>model_utility</code> function will return three rows: one for the policy of contacting everyone (threshold = 0), one for threshold = 0.5, and one for the policy of contacting no one (marked as threshold = NA).</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># add a column for the wizard model</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>d<span class="op">$</span>wizard &lt;-<span class="st"> </span><span class="kw">with</span>(d, <span class="kw">ifelse</span>(converted, <span class="fl">1.0</span>, <span class="fl">0.0</span>))</span>
<span id="cb9-3"><a href="#cb9-3"></a></span>
<span id="cb9-4"><a href="#cb9-4"></a><span class="co"># calculate the wizard&#39;s model utilities</span></span>
<span id="cb9-5"><a href="#cb9-5"></a>wizard_values &lt;-<span class="st"> </span><span class="kw">model_utility</span>(d, </span>
<span id="cb9-6"><a href="#cb9-6"></a>                               <span class="dt">model_name =</span> <span class="st">&#39;wizard&#39;</span>,</span>
<span id="cb9-7"><a href="#cb9-7"></a>                               <span class="dt">outcome_name =</span> <span class="st">&#39;converted&#39;</span>)</span>
<span id="cb9-8"><a href="#cb9-8"></a>wizard_values[, <span class="kw">c</span>(<span class="st">&quot;threshold&quot;</span>, <span class="st">&quot;count_taken&quot;</span>, </span>
<span id="cb9-9"><a href="#cb9-9"></a>                  <span class="st">&quot;fraction_taken&quot;</span>, <span class="st">&quot;total_value&quot;</span>)] <span class="op">%.&gt;%</span></span>
<span id="cb9-10"><a href="#cb9-10"></a><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>(.)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th style="text-align: right;">threshold</th>
<th style="text-align: right;">count_taken</th>
<th style="text-align: right;">fraction_taken</th>
<th style="text-align: right;">total_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">10000</td>
<td style="text-align: right;">1.0000</td>
<td style="text-align: right;">-39400.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">106</td>
<td style="text-align: right;">0.0106</td>
<td style="text-align: right;">10168.94</td>
</tr>
<tr class="odd">
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">97.88</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="co"># amount of potential value in this population</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>potential =<span class="st"> </span>wizard_values<span class="op">$</span>total_value[<span class="dv">2</span>]</span>
<span id="cb10-3"><a href="#cb10-3"></a></span>
<span id="cb10-4"><a href="#cb10-4"></a><span class="co"># what we realized</span></span>
<span id="cb10-5"><a href="#cb10-5"></a>realized =<span class="st"> </span>best_info<span class="op">$</span>total_value</span>
<span id="cb10-6"><a href="#cb10-6"></a></span>
<span id="cb10-7"><a href="#cb10-7"></a><span class="co"># fraction realized</span></span>
<span id="cb10-8"><a href="#cb10-8"></a>frac_realized =<span class="st"> </span>realized<span class="op">/</span>potential</span></code></pre></div>
<p>The <code>threshold = 0.5</code> row tells us that the potential value of this population sample is $10168.94, of which our model realized $2159.45, or 21.2% of the total available value.</p>
<h3 id="advanced-variable-utilities">Advanced: Variable Utilities</h3>
<p>In the above example, we assigned constant utilities and costs to the data set. Here, instead of assuming a fixed revenue of $100 dollars on conversions, we’ll assume that projected potential revenue varies by prospect (with an average of $100). This potential value could be contract sizes that we are bidding on, which varies from prospect to prospect.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="co"># replace the true positive value with a varying value</span></span>
<span id="cb11-2"><a href="#cb11-2"></a>d<span class="op">$</span>true_positive_value &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="kw">nrow</span>(d), <span class="dt">mean =</span> <span class="dv">100</span>, <span class="dt">sd =</span> <span class="dv">25</span>) <span class="op">-</span><span class="st"> </span><span class="dv">5</span>   <span class="co"># revenue - cost</span></span>
<span id="cb11-3"><a href="#cb11-3"></a></span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="co"># recalculate the values and potential</span></span>
<span id="cb11-5"><a href="#cb11-5"></a>values &lt;-<span class="st"> </span><span class="kw">model_utility</span>(d, </span>
<span id="cb11-6"><a href="#cb11-6"></a>                        <span class="dt">model_name =</span> <span class="st">&#39;predicted_probability&#39;</span>, </span>
<span id="cb11-7"><a href="#cb11-7"></a>                        <span class="dt">outcome_name =</span> <span class="st">&#39;converted&#39;</span>)</span>
<span id="cb11-8"><a href="#cb11-8"></a></span>
<span id="cb11-9"><a href="#cb11-9"></a>wizard_values &lt;-<span class="st"> </span><span class="kw">model_utility</span>(d, </span>
<span id="cb11-10"><a href="#cb11-10"></a>                               <span class="dt">model_name =</span> <span class="st">&#39;wizard&#39;</span>,</span>
<span id="cb11-11"><a href="#cb11-11"></a>                               <span class="dt">outcome_name =</span> <span class="st">&#39;converted&#39;</span>)</span></code></pre></div>
<p>Here we replot the utility curve.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>vhigh &lt;-<span class="st"> </span><span class="kw">subset</span>(values, threshold <span class="op">&gt;=</span><span class="st"> </span>t_bound) <span class="co"># just look at thresholds &gt;= t_bound</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(vhigh, <span class="kw">aes</span>(<span class="dt">x =</span> threshold, <span class="dt">y =</span> total_value)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb12-3"><a href="#cb12-3"></a><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb12-4"><a href="#cb12-4"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Estimated model utility as a function of threshold, variable utility case&quot;</span>)</span>
<span id="cb12-5"><a href="#cb12-5"></a></span>
<span id="cb12-6"><a href="#cb12-6"></a><span class="co"># find the maximum utility</span></span>
<span id="cb12-7"><a href="#cb12-7"></a>max_ix &lt;-<span class="st"> </span><span class="kw">which.max</span>(vhigh<span class="op">$</span>total_value)</span>
<span id="cb12-8"><a href="#cb12-8"></a>best_threshold &lt;-<span class="st"> </span>vhigh<span class="op">$</span>threshold[max_ix]</span>
<span id="cb12-9"><a href="#cb12-9"></a></span>
<span id="cb12-10"><a href="#cb12-10"></a>p <span class="op">+</span><span class="st"> </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> best_threshold, <span class="dt">linetype=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="UtilityExample_files/figure-gfm/unnamed-chunk-10-1.png" /><!-- --></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="co"># print out some information about the optimum</span></span>
<span id="cb13-2"><a href="#cb13-2"></a>vhigh[max_ix, <span class="kw">c</span>(<span class="st">&quot;threshold&quot;</span>, <span class="st">&quot;count_taken&quot;</span>, <span class="st">&quot;fraction_taken&quot;</span>, <span class="st">&quot;total_value&quot;</span>)] <span class="op">%.&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>(.)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">threshold</th>
<th style="text-align: right;">count_taken</th>
<th style="text-align: right;">fraction_taken</th>
<th style="text-align: right;">total_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">9574</td>
<td style="text-align: right;">0.021672</td>
<td style="text-align: right;">427</td>
<td style="text-align: right;">0.0427</td>
<td style="text-align: right;">2041.251</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="co"># compare to potential</span></span>
<span id="cb14-2"><a href="#cb14-2"></a>wizard_values[<span class="dv">2</span>, <span class="kw">c</span>(<span class="st">&quot;threshold&quot;</span>, <span class="st">&quot;count_taken&quot;</span>, <span class="st">&quot;fraction_taken&quot;</span>, <span class="st">&quot;total_value&quot;</span>)] <span class="op">%.&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3"></a><span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>(.)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">threshold</th>
<th style="text-align: right;">count_taken</th>
<th style="text-align: right;">fraction_taken</th>
<th style="text-align: right;">total_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">106</td>
<td style="text-align: right;">0.0106</td>
<td style="text-align: right;">10136.36</td>
</tr>
</tbody>
</table>
<h3 id="reporting-uncertainty">Reporting Uncertainty</h3>
<p>Up until now, we have returned a point utility estimate. It’s better to use a distribution, or at least an estimate of uncertainty. In our next note, we will deal with estimating and reporting uncertainty.</p>
<h2 id="conclusion">Conclusion</h2>
<p>We have shown how to select a classifier threshold directly from policy utility, using <code>sigr::model_utility()</code>. Thinking in terms of utility is simple, because it’s already the language of your business partners.</p>
